---
apiVersion: v1
kind: Namespace
metadata:
  name: easy-housing-app
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: easy-housing-webapp-deployment
#  namespace: easy-housing-app
#  labels:
#    app: easy-housing-webapp
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: easy-housing-webapp
#  template:
#    metadata:
#      labels:
#        app: easy-housing-webapp
#    spec:
#      containers:
#        - name: easy-housing-webapp
#          image: 10.0.0.108:32000/easy-housing-webapp:thomas-latest
#          ports:
#            - containerPort: 3000
#          imagePullPolicy: Always
#          resources:
#            limits:
#              cpu: "500m"
#              memory: "256Mi"
#            requests:
#              cpu: "250m"
#              memory: "128Mi"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: easy-housing-web-service
#  namespace: easy-housing-app
#spec:
#  selector:
#    app: easy-housing-webapp
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 3000
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: easy-housing-gql-deployment
#  namespace: easy-housing-app
#  labels:
#    app: easy-housing-gql
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: easy-housing-gql
#  template:
#    metadata:
#      labels:
#        app: easy-housing-gql
#    spec:
#      containers:
#        - name: easy-housing-gql
#          image: 10.0.0.108:32000/easy-housing-gql-gateway:latest
#          ports:
#            - containerPort: 8888
#          resources:
#            limits:
#              cpu: "500m"
#              memory: "128Mi"
#            requests:
#              cpu: "250m"
#              memory: "64Mi"
#          imagePullPolicy: Always
#          envFrom:
#            - secretRef:
#                name: google-client-data
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: easy-housing-app-gql-service
#  namespace: easy-housing-app
#spec:
#  selector:
#    app: easy-housing-gql
#  ports:
#    - name: graphql
#      protocol: TCP
#      port: 8888
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: easy-housing-app-gql-nodeport-service
#  namespace: easy-housing-app
#spec:
#  type: NodePort
#  selector:
#    app: easy-housing-gql
#  ports:
#    - name: graphql-nodeport
#      protocol: TCP
#      port: 8890
#      targetPort: 8888
#      nodePort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-housing-server-deployment
  namespace: easy-housing-app
  labels:
    app: easy-housing-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easy-housing-server
  template:
    metadata:
      labels:
        app: easy-housing-server
    spec:
      containers:
        - name: easy-housing-server
          image: 10.0.0.108:32000/easy-housing-server:latest
          ports:
            - containerPort: 9000
          livenessProbe:
            grpc:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: easy-housing-app-psql-db-superuser
---
apiVersion: v1
kind: Service
metadata:
  name: easy-housing-app-server-service
  namespace: easy-housing-app
spec:
  selector:
    app: easy-housing-server
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: easy-housing-app-psql-db
  namespace: easy-housing-app
spec:
  instances: 1
  storage:
    storageClass: ssd-hostpath
    size: 5Gi
    pvcTemplate:
      selector:
        matchLabels:
          role: storage
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: easy-housing-app-psqldb-nodeport-service
#  namespace: easy-housing-app
#spec:
#  type: NodePort
#  selector:
#    cnpg.io/cluster: easy-housing-app-psql-db
#  ports:
#    - name: psql-db-nodeport
#      protocol: TCP
#      port: 5433
#      targetPort: 5432
#      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: easy-housing-app-server-nodeport-service
  namespace: easy-housing-app
spec:
  type: NodePort
  selector:
    app: easy-housing-server
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
      nodePort: 31003
