// Code generated by proroc-gen-graphql, DO NOT EDIT.
package api

import (
	"context"

	"github.com/graphql-go/graphql"
	"github.com/pkg/errors"
	"github.com/ysugimoto/grpc-graphql-gateway/runtime"
	"google.golang.org/grpc"
)

var (
	gql__type_EchoResponse  *graphql.Object      // message EchoResponse in api/easy-housing.proto
	gql__type_EchoRequest   *graphql.Object      // message EchoRequest in api/easy-housing.proto
	gql__input_EchoResponse *graphql.InputObject // message EchoResponse in api/easy-housing.proto
	gql__input_EchoRequest  *graphql.InputObject // message EchoRequest in api/easy-housing.proto
)

func Gql__type_EchoResponse() *graphql.Object {
	if gql__type_EchoResponse == nil {
		gql__type_EchoResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_EchoResponse",
			Fields: graphql.Fields{
				"message": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_EchoResponse
}

func Gql__type_EchoRequest() *graphql.Object {
	if gql__type_EchoRequest == nil {
		gql__type_EchoRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Api_Type_EchoRequest",
			Fields: graphql.Fields{
				"message": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_EchoRequest
}

func Gql__input_EchoResponse() *graphql.InputObject {
	if gql__input_EchoResponse == nil {
		gql__input_EchoResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_EchoResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"message": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_EchoResponse
}

func Gql__input_EchoRequest() *graphql.InputObject {
	if gql__input_EchoRequest == nil {
		gql__input_EchoRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Api_Input_EchoRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"message": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_EchoRequest
}

// graphql__resolver_EasyHousing is a struct for making query, mutation and resolve fields.
// This struct must be implemented runtime.SchemaBuilder interface.
type graphql__resolver_EasyHousing struct {

	// Automatic connection host
	host string

	// grpc dial options
	dialOptions []grpc.DialOption

	// grpc client connection.
	// this connection may be provided by user
	conn *grpc.ClientConn
}

// new_graphql_resolver_EasyHousing creates pointer of service struct
func new_graphql_resolver_EasyHousing(conn *grpc.ClientConn) *graphql__resolver_EasyHousing {
	return &graphql__resolver_EasyHousing{
		conn: conn,
		host: "easy-housing-app-server-service:9000",
		dialOptions: []grpc.DialOption{
			grpc.WithInsecure(),
		},
	}
}

// CreateConnection() returns grpc connection which user specified or newly connected and closing function
func (x *graphql__resolver_EasyHousing) CreateConnection(ctx context.Context) (*grpc.ClientConn, func(), error) {
	// If x.conn is not nil, user injected their own connection
	if x.conn != nil {
		return x.conn, func() {}, nil
	}

	// Otherwise, this handler opens connection with specified host
	conn, err := grpc.DialContext(ctx, x.host, x.dialOptions...)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

// GetQueries returns acceptable graphql.Fields for Query.
func (x *graphql__resolver_EasyHousing) GetQueries(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{
		"echo": &graphql.Field{
			Type: Gql__type_EchoResponse(),
			Args: graphql.FieldConfigArgument{
				"message": &graphql.ArgumentConfig{
					Type: graphql.String,
				},
			},
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				var req EchoRequest
				if err := runtime.MarshalRequest(p.Args, &req, false); err != nil {
					return nil, errors.Wrap(err, "Failed to marshal request for echo")
				}
				client := NewEasyHousingClient(conn)
				resp, err := client.Echo(p.Context, &req)
				if err != nil {
					return nil, errors.Wrap(err, "Failed to call RPC Echo")
				}
				return resp, nil
			},
		},
	}
}

// GetMutations returns acceptable graphql.Fields for Mutation.
func (x *graphql__resolver_EasyHousing) GetMutations(conn *grpc.ClientConn) graphql.Fields {
	return graphql.Fields{}
}

// Register package divided graphql handler "without" *grpc.ClientConn,
// therefore gRPC connection will be opened and closed automatically.
// Occasionally you may worry about open/close performance for each handling graphql request,
// then you can call RegisterEasyHousingGraphqlHandler with *grpc.ClientConn manually.
func RegisterEasyHousingGraphql(mux *runtime.ServeMux) error {
	return RegisterEasyHousingGraphqlHandler(mux, nil)
}

// Register package divided graphql handler "with" *grpc.ClientConn.
// this function accepts your defined grpc connection, so that we reuse that and never close connection inside.
// You need to close it maunally when application will terminate.
// Otherwise, you can specify automatic opening connection with ServiceOption directive:
//
//	service EasyHousing {
//	   option (graphql.service) = {
//	       host: "host:port"
//	       insecure: true or false
//	   };
//
//	   ...with RPC definitions
//	}
func RegisterEasyHousingGraphqlHandler(mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return mux.AddHandler(new_graphql_resolver_EasyHousing(conn))
}
