// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/easy-housing.proto

package api

import (
	"google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_api_easy_housing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_easy_housing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_api_easy_housing_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_api_easy_housing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_easy_housing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_api_easy_housing_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_api_easy_housing_proto protoreflect.FileDescriptor

const file_api_easy_housing_proto_rawDesc = "" +
	"\n" +
	"\x16api/easy-housing.proto\x12\feasy_housing\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2N\n" +
	"\vEasyHousing\x12?\n" +
	"\x04Echo\x12\x19.easy_housing.EchoRequest\x1a\x1a.easy_housing.EchoResponse\"\x00B\x12Z\x10easy-housing/apib\beditionsp\xe8\a"

var (
	file_api_easy_housing_proto_rawDescOnce sync.Once
	file_api_easy_housing_proto_rawDescData []byte
)

func file_api_easy_housing_proto_rawDescGZIP() []byte {
	file_api_easy_housing_proto_rawDescOnce.Do(func() {
		file_api_easy_housing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_easy_housing_proto_rawDesc), len(file_api_easy_housing_proto_rawDesc)))
	})
	return file_api_easy_housing_proto_rawDescData
}

var file_api_easy_housing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_easy_housing_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: easy_housing.EchoRequest
	(*EchoResponse)(nil), // 1: easy_housing.EchoResponse
}
var file_api_easy_housing_proto_depIdxs = []int32{
	0, // 0: easy_housing.EasyHousing.Echo:input_type -> easy_housing.EchoRequest
	1, // 1: easy_housing.EasyHousing.Echo:output_type -> easy_housing.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_easy_housing_proto_init() }
func file_api_easy_housing_proto_init() {
	if File_api_easy_housing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_easy_housing_proto_rawDesc), len(file_api_easy_housing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_easy_housing_proto_goTypes,
		DependencyIndexes: file_api_easy_housing_proto_depIdxs,
		MessageInfos:      file_api_easy_housing_proto_msgTypes,
	}.Build()
	File_api_easy_housing_proto = out.File
	file_api_easy_housing_proto_goTypes = nil
	file_api_easy_housing_proto_depIdxs = nil
}
